name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        python -m unittest test_app.py

  deploy:
    needs: build # This refers to the job named 'build'
    runs-on: ubuntu-latest
    steps:
    - name: Simple deploy step
      run: echo "Starting the deployment process..."
    - name: Another simple deploy step
      run: echo "Deployment complete!"

  notify:
    needs: deploy # This ensures 'notify' runs after 'deploy' completes successfully
    runs-on: ubuntu-latest
    steps:
      - name: Send notification
        run: echo "Deployment to production (or wherever!) has finished."